import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    //absolute: "",
    default: "Next js Course",
    template: "%s | nextjs course" // it can be replaced by absolute from any child metadata
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{textAlign: "center"}}>
        <header style={{ backgroundColor: "lightblue", padding: '1rem' }}>Header <Link href="/login" 
          style={{border: "1px solid black", borderRadius: "6px", padding: "10px 15px", textDecoration: "none", color: "white", fontWeight: "bold", background: "black"}}>Login</Link></header>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: '1rem' }}>Footer</footer>
      </body>
    </html>
  )
}
